spring:
  application:
    name: projectCRUD

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vladpr
    username: postgres
    password: 247316

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

dadata:
  token: "78adbc9dace23b13c854aeff92669c38d2d389cb"
  secret-token: "1aa7f06ab075087da6cb4d92236980a133f18263"
  api-url: "https://cleaner.dadata.ru/api/v1/clean/address"

two-gis:
  url: "https://routing.api.2gis.com/routing/7.0.0/global?key=738fa2b2-0290-4ebb-bd60-bcb919219e2b"

telegram:
  service:
    url: "http://localhost:8081/api/core"

buffer-time-sec: 1800