spring:
  application:
    name: projectCRUD

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

dadata:
  token: ${DADATA_TOKEN}
  secret-token: ${DADATA_SECRET_TOKEN}
  api-url: ${DADATA_API_URL}

two-gis:
  url: ${TWO_GIS_URL}

telegram:
  service:
    url: ${TELEGRAM_SERVICE_URL}

buffer-time-sec: 1800