spring:
  application:
    name: projectCRUD

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vladpr
    username: postgres
    password: 247316

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

dadata:
  token: "c7556dfd858a89a83b6bcf29b3a4f9cd87d266fb"
  secret-token: "36d50b82413e19baf08a0b2d60893aca393a255e"
  api-url: "https://cleaner.dadata.ru/api/v1/clean/address"