spring:
  application:
    name: telegram-bot-service

server:
  port: 8081

telegram:
  bot:
    token: "8583495884:AAH9DCx7vRQF0tqAlbKoyP9awW-cu7qPA24"

core:
  service:
    url: "http://localhost:8080/api/telegram"