spring:
  application:
    name: telegram-bot-service
    profiles:
      active: ${SPRING_APPLICATION_PROFILE:dev}

server:
  port: 8081

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

environment: ${ENVIRONMENT:dev}

core:
  service:
    url: ${CORE_SERVICE_URL}