name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: notify-service build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./myProject/prCRUD
          file: ./myProject/prCRUD/Dockerfile
          push: true
          tags: defiiz/notify-service:latest

      - name: telegram-bot-service build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./myProject/telegram-bot-service
          file: ./myProject/telegram-bot-service/Dockerfile
          push: true
          tags: defiiz/telegram-bot-service:latest

  push_compose:
    name: Push docker-compose.yml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: 194.87.238.231
          username: vlad
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./docker-compose.yml"
          target: "~"

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [build_and_push_images, push_compose]

    steps:
      - name: Connect with ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 194.87.238.231
          username: vlad
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo DB_USER = ${{ secrets.DB_USER }} > .env
            echo DB_PASSWORD = ${{ secrets.DB_PASSWORD }} >> .env
            echo DB_NAME = ${{ secrets.DB_NAME }}  >> .env
            echo ENVIRONMENT = ${{ secrets.ENVIRONMENT }}  >> .env
            echo SPRING_PROFILES_ACTIVE = ${{ secrets.SPRING_PROFILES_ACTIVE }} >> .env
            echo DADATA_TOKEN = ${{ secrets.DADATA_TOKEN }} >> .env
            echo DADATA_SECRET_TOKEN = ${{ secrets.DADATA_SECRET_TOKEN }} >> .env
            echo DADATA_API_URL = ${{ secrets.DADATA_API_URL }}  >> .env
            echo TWO_GIS_URL = ${{ secrets.TWO_GIS_URL }} >> .env
            echo TELEGRAM_SERVICE_URL = ${{ secrets.TELEGRAM_SERVICE_URL }} >> .env
            echo TELEGRAM_BOT_TOKEN = ${{ secrets.TELEGRAM_BOT_TOKEN }} >> .env
            echo CORE_SERVICE_URL = ${{ secrets.CORE_SERVICE_URL }} >> .env
            
            sudo docker compose down
            sudo docker pull defiiz/notify-service:latest
            sudo docker pull defiiz/telegram-bot-service:latest
            sudo docker compose up -d