name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Logit to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Notify_Service Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./myProject/prCRUD
          file: ./myProject/prCRUD/Dockerfile
          push: true
          tags: defiiz/notify-service:latest

      - name: Telegram-Bot-Service Build adn Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./myProject/telegram-bot-service
          file: ./myProject/telegram-bot-service/Dockerfile
          push: true
          tags: defiiz/telegram-bot-service:latest